{
 "title": "Calculator Application Telemetry (Prometheus)",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "Calculator app",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Average Request Duration",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(request_duration_seconds_sum[2m]) / rate(request_duration_seconds_count[2m])",
       "legendFormat": "Average Request Duration"
      }
     ]
    },
    {
     "title": "Average Requests per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 3 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(request_operations_total[2m])",
       "legendFormat": "Average Requests per Second"
      }
     ]
    },
    {
     "title": "Request Duration (sliced per operation)",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 0, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "rate(add_request_duration_seconds_sum[2m]) / rate(add_request_duration_seconds_count[2m])",
       "legendFormat": "ADD_requests"
      },
      {
       "expr": "rate(substract_request_duration_seconds_sum[2m]) / rate(substract_request_duration_seconds_count[2m])",
       "legendFormat": "SUBSTRACT_requests"
      },
      {
       "expr": "rate(division_request_duration_seconds_sum[2m])/rate(division_request_duration_seconds_count[2m])",
       "legendFormat": "DIVISION_requests"
      },
      {
       "expr": "rate(random_request_duration_seconds_sum[2m])/rate(random_request_duration_seconds_count[2m])",
       "legendFormat": "RANDOM_requests"
      }
     ]
    },
    {
     "title": "Requests sliced. Per Second",
     "type": "graph",
     "gridPos": { "h": 8, "w": 11, "x": 11, "y": 11 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "irate(add_request_operations_total[2m])",
       "legendFormat": "ADD_requests"
      },
      {
       "expr": "irate(substract_request_operations_total[2m])",
       "legendFormat": "SUBSTRACT_requests"
      },
      {
       "expr": "irate(division_request_operations_total[2m])",
       "legendFormat": "DIVISION_requests"
      },
      {
       "expr": "irate(random_request_operations_total[2m])",
       "legendFormat": "RANDOM_requests"
      }
     ]
    }
   ]
  }
 ]
}